spring:
  datasource:
    url: jdbc:h2:mem:${spring.application.name};DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        hbm2ddl:
          auto: create-drop
        show_sql: false
        use_sql_comments: false
        format_sql: false
        dialect: org.hibernate.dialect.H2Dialect
  sql:
    init:
      mode: always

  h2:
    console:
      enabled: true
      path: /h2-console