spring:
  application:
    name: determination-mutatant-dna
  config:
    name: ${spring.application.name}-${SPRING_PROFILE}-${APP_VERSION}
  profiles:
    active: ${SPRING_PROFILE}

server:
  port: ${PORT:8080}