spring:
  datasource:
    url: jdbc:mariadb://45.7.231.125:3306/c5devsistema2?serverTimezone=America/Santiago&zeroDateTimeBehavior=convertToNull
    username: c5devsistema
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        hbm2ddl:
          auto: none
        show_sql: false
        use_sql_comments: false
        format_sql: false
        dialect: org.hibernate.dialect.MariaDB10Dialect
  sql:
    init:
      mode: never